name: Android CI & Release
'on':
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleRelease
        env:
          GITHUB_RUN_NUMBER: '${{ github.run_number }}'
          GITHUB_REF_NAME: '${{ github.ref_name }}'
      - name: Setup build tool version variable
        shell: bash
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
          echo Last build tool version is: $BUILD_TOOL_VERSION
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: '${{ secrets.KEYSTORE }}'
          alias: '${{ secrets.KEY_ALIAS }}'
          keyStorePassword: '${{ secrets.KEYSTORE_PASSWORD }}'
          keyPassword: '${{ secrets.KEY_PASSWORD }}'
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      - name: Rename Signed APK
        # Only run if signing succeeded AND we are pushing a tag
        if: success() && startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          OLD_PATH="${{ steps.sign_app.outputs.signedReleaseFile }}"
          NEW_NAME="LyriSync-${{ github.ref_name }}.apk"
          NEW_PATH="app/build/outputs/apk/release/$NEW_NAME"
          
          mv "$OLD_PATH" "$NEW_PATH"
          
          # Save the new path for the next step
          echo "NEW_APK_PATH=$NEW_PATH" >> $GITHUB_ENV
          echo "Renamed APK to $NEW_NAME"

      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          # Use the environment variable set in the Rename step
          files: ${{ env.NEW_APK_PATH }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}